import PDFDocument from 'pdfkit';
import QRCode from 'qrcode';

export async function generatePDF(text: string, caseId: string, watermark?: string) {
  const doc = new PDFDocument({ size: 'A4', margin: 50 });
  const chunks: Buffer[] = [];
  doc.on('data', c => chunks.push(c));
  doc.fontSize(12).text(text, { align: 'justify' });
  doc.moveDown().fontSize(8).fillColor('gray').text('Generated by Disput.ai', { align: 'center' });

  if (watermark) {
    doc.fontSize(80).fillColor('gray', 0.3);
    doc.rotate(45, { origin: [doc.page.width/2, doc.page.height/2] });
    doc.text(watermark, doc.page.width/4, doc.page.height/2, { align: 'center', opacity: 0.2 });
    doc.rotate(-45);
    doc.fillColor('black').fontSize(12);
  }

  const qrDataUrl = await QRCode.toDataURL(`https://disput.ai/verify?case=${caseId}`);
  const pngBase64 = qrDataUrl.split(',')[1];
  const qrBuffer = Buffer.from(pngBase64, 'base64');
  const qrSize = 100;
  doc.image(qrBuffer, doc.page.width - qrSize - 50, doc.page.height - qrSize - 50, { width: qrSize });
  doc.end();
  return Buffer.concat(chunks);
}
